whites = ["white", "ivory", "ivory1", "mintcream", "snow", "snow1", "honeydew", "honeydew1",
 "floralwhite", "ghostwhite", "cornsilk", "cornsilk1", "seashell", "seashell1",
 "oldlace", "whitesmoke", "beige", "linen", "antiquewhite1", "ivory2",
 "antiquewhite", "honeydew2", "snow2", "cornsilk2", "seashell2", "navajowhite",
 "navajowhite1", "antiquewhite2", "navajowhite2", "ivory3", "snow3", "honeydew3",
 "cornsilk3", "seashell3", "antiquewhite3", "silver", "navajowhite3",
 "ivory4", "snow4", "honeydew4", "cornsilk4", "seashell4", "antiquewhite4",
 "navajowhite4"] 

reds = ["lightsalmon","lightsalmon1","salmon1","lightsalmon2","darksalmon","coral",
"salmon","lightcoral","salmon2","coral1","indianred1","tomato","tomato1",
"lightsalmon3","coral2","indianred2","tomato2","salmon3","firebrick1",
"indianred","red","red1","coral3","firebrick2","indianred3","tomato3",
"red2","crimson","firebrick3","red3","lightsalmon4","salmon4","firebrick",
"coral4","indianred4","tomato4","firebrick4","darkred","red4"]

oranges = ["orange","orange1","orange2","darkorange","darkorange1","darkorange2",
"orange3","orangered","orangered1","darkorange3","orangered2",
"orangered3","orange4","darkorange4","orangered4"]

yellows = ["lightyellow","lightyellow1","lemonchiffon","lemonchiffon1",
"lightgoldenrodyellow","yellow","yellow1","khaki1","lightyellow2",
"lightgoldenrod1","wheat1","lemonchiffon2","yellow2","palegoldenrod",
"khaki","khaki2","wheat","lightgoldenrod","lightgoldenrod2","wheat2",
"gold","gold1","gold2","lightyellow3","goldenrod1","lemonchiffon3",
"yellow3","darkgoldenrod1","khaki3","lightgoldenrod3","goldenrod2",
"wheat3","darkgoldenrod2","darkkhaki","gold3","goldenrod","goldenrod3",
"darkgoldenrod3","darkgoldenrod","lightyellow4","lemonchiffon4",
"yellow4","khaki4","lightgoldenrod4","wheat4","gold4","goldenrod4",
"darkgoldenrod4"]

greens = ["darkseagreen1","darkolivegreen1","olivedrab1","aquamarine",
"aquamarine1","palegreen1","greenyellow","palegreen","chartreuse","chartreuse1",
"seagreen1","darkseagreen2","lawngreen","springgreen","springgreen1",
"darkolivegreen2","green1","lime","olivedrab2","mediumspringgreen",
"lightgreen","palegreen2","aquamarine2","chartreuse2","seagreen2",
"springgreen2","green2","darkseagreen3","darkolivegreen3","olivedrab3",
"yellowgreen","palegreen3","aquamarine3","mediumaquamarine","chartreuse3",
"seagreen3","springgreen3","limegreen","darkseagreen","green3",
"lightseagreen","mediumseagreen","olivedrab","darkseagreen4",
"darkolivegreen4","olivedrab4","aquamarine4","palegreen4","olive",
"seagreen","seagreen4","chartreuse4","forestgreen","springgreen4",
"green4","green","darkolivegreen","darkgreen"]

cyans = ["lightcyan", "lightcyan1", "paleturquoise1", "lightcyan2", "aqua", 
"cyan", "cyan1", "paleturquoise", "paleturquoise2", "turquoise1", 
"cyan2", "turquoise2", "turquoise", "lightcyan3", "paleturquoise3", 
"mediumturquoise", "darkturquoise", "cyan3", "turquoise3", "lightcyan4", 
"paleturquoise4", "cyan4", "darkcyan", "turquoise4", "teal"]

blues =
["aliceblue", "azure", "azure1", "azure2", "azure3", "azure4", "blue",
"blue1", "blue2", "blue3", "blue4", "cadetblue", "cadetblue1", "cadetblue2",
"cadetblue3", "cadetblue4", "cornflowerblue", "darkblue", "darkslateblue",
"darkslategray", "darkslategray1", "darkslategray2", "darkslategray3",
"darkslategray4", "darkslategrey", "deepskyblue", "deepskyblue1", "deepskyblue2",
"deepskyblue3", "deepskyblue4", "dodgerblue", "dodgerblue1", "dodgerblue2",
"dodgerblue3", "dodgerblue4", "gainsboro", "indigo", "lightblue", "lightblue1",
"lightblue2", "lightblue3", "lightblue4", "lightskyblue", "lightskyblue1",
"lightskyblue2", "lightskyblue3", "lightskyblue4", "lightslateblue", "lightslategray",
"lightslategrey", "lightsteelblue", "lightsteelblue1", "lightsteelblue2",
"lightsteelblue3", "lightsteelblue4", "mediumblue", "mediumslateblue",
"midnightblue", "navy", "navyblue", "powderblue", "royalblue", "royalblue1",
"royalblue2", "royalblue3", "royalblue4", "skyblue", "skyblue1", "skyblue2",
"skyblue3", "skyblue4", "slateblue", "slateblue1", "slateblue2", "slateblue3",
"slateblue4", "slategray", "slategray1", "slategray2", "slategray3", "slategray4",
"slategrey", "steelblue", "steelblue1", "steelblue2", "steelblue3", "steelblue4"]

purples = ["lavenderblush", "lavenderblush1", "thistle1", "mistyrose", "mistyrose1", 
"lavender", "lavenderblush2", "thistle2", "mistyrose2", "plum1", "thistle", 
"lavenderblush3", "plum2", "thistle3", "mistyrose3", "plum", "orchid1", 
"violet", "plum3", "orchid2", "mediumorchid1", "mediumpurple1", "orchid",
"fuchsia", "magenta", "magenta1", "mediumorchid2", "orchid3", "mediumpurple2", 
"magenta2", "lavenderblush4", "mediumpurple", "darkorchid1", "mediumorchid",
"mistyrose4", "thistle4", "mediumorchid3", "mediumpurple3", "darkorchid2", 
"magenta3", "plum4", "purple1", "purple2", "darkorchid3", "darkorchid", 
"blueviolet", "orchid4", "darkviolet", "purple3", "mediumorchid4", 
"mediumpurple4", "rebeccapurple", "darkmagenta", "magenta4", "purple", 
"darkorchid4", "purple4"]

pinks = ["pink","lightpink","pink1","lightpink1","pink2","lightpink2",
"palevioletred1","hotpink1","pink3","hotpink","palevioletred2",
"lightpink3","hotpink2","palevioletred","maroon1","violetred1",
"palevioletred3","deeppink","deeppink1","hotpink3","violetred2",
"maroon2","deeppink2","violetred3","maroon3","violetred","pink4",
"deeppink3","lightpink4","mediumvioletred","palevioletred4",
"hotpink4","violetred4","maroon4","deeppink4","maroon"]

browns = ["papayawhip", "blanchedalmond", "bisque", "bisque1", "moccasin",
"peachpuff", "peachpuff1", "burlywood1", "bisque2", "peachpuff2", 
"rosybrown1", "burlywood2", "rosybrown2", "burlywood", "bisque3", "tan1", 
"tan", "sandybrown", "peachpuff3", "burlywood3", "tan2", "rosybrown3", 
"sienna1", "chocolate1", "rosybrown", "sienna2", "chocolate2", "peru",
 "tan3", "brown1", "chocolate", "sienna3", "chocolate3", "brown2", 
 "bisque4", "peachpuff4", "burlywood4", "rosybrown4", "brown3", "sienna", 
 "tan4", "sienna4", "brown", "chocolate4", "saddlebrown", "brown4"] 

 grays = ["gray100", "gray99", "gray98", "gray97", "gray96", "gray95", 
"gray94", "gray93", "gray92", "gray91", "gray90", "gray89", "gray88", 
"gray87", "gray86", "gray85", "gray84", "gray83", "lightgray", "gray82", 
"gray81", "gray80", "gray79", "gray78", "gray77", "gray76", "gray75", 
"gray74", "gray73", "gray72", "gray71", "gray70", "gray69", "gray68", 
"gray67", "darkgray", "gray66", "gray65", "gray64", "gray63", "gray62", 
"gray61", "gray60", "gray59", "gray58", "gray57", "gray56", "gray55", 
"gray54", "gray53", "gray52", "gray51", "gray", "gray50", "gray49", 
"gray48", "gray47", "gray46", "gray45", "gray44", "gray43", "gray42", 
"dimgray", "gray41", "gray40", "gray39", "gray38", "gray37", "gray36", 
"gray35", "gray34", "gray33", "gray32", "gray31", "gray30", "gray29", 
"gray28", "gray27", "gray26", "gray25", "gray24", "gray23", "gray22", 
"gray21", "gray20", "gray19", "gray18", "gray17", "gray16", "gray15", 
"gray14", "gray13", "gray12", "gray11", "gray10", "gray9", "gray8", 
"gray7", "gray6", "gray5", "gray4", "gray3", "gray2", "gray1", "gray0",
"black"]

greys = ["grey100", "grey99", "grey98", "grey97", "grey96", "grey95", 
"grey94", "grey93", "grey92", "grey91", "grey90", "grey89", "grey88", 
"grey87", "grey86", "grey85", "grey84", "grey83", "lightgrey", "grey82", 
"grey81", "grey80", "grey79", "grey78", "grey77", "grey76", "grey75", 
"grey74", "grey73", "grey72", "grey71", "grey70", "grey69", "grey68", 
"grey67", "derkgrey", "grey66", "grey65", "grey64", "grey63", "grey62", 
"grey61", "grey60", "grey59", "grey58", "grey57", "grey56", "grey55", 
"grey54", "grey53", "grey52", "grey51", "grey", "grey50", "grey49", 
"grey48", "grey47", "grey46", "grey45", "grey44", "grey43", "grey42", 
"dimgrey", "grey41", "grey40", "grey39", "grey38", "grey37", "grey36", 
"grey35", "grey34", "grey33", "grey32", "grey31", "grey30", "grey29", 
"grey28", "grey27", "grey26", "grey25", "grey24", "grey23", "grey22", 
"grey21", "grey20", "grey19", "grey18", "grey17", "grey16", "grey15", 
"grey14", "grey13", "grey12", "grey11", "grey10", "grey9", "grey8", 
"grey7", "grey6", "grey5", "grey4", "grey3", "grey2", "grey1", "grey0",
"black"]